[project]
name = "python-template"
version = "0.1.0"
description = "{{cookiecutter.project_short_description}}"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "opentelemetry-api>=1.32.1",
    "opentelemetry-exporter-otlp>=1.32.1",
    "opentelemetry-instrumentation-logging>=0.53b1",
    "opentelemetry-sdk>=1.32.1",
    "prometheus-client>=0.21.1",
]

[dependency-groups]
dev = [
    "pre-commit",
    "ruff",
    "rope",
    "python-lsp-server[all]",
    "python-lsp-black",
    "python-lsp-isort",
    "python-lsp-ruff",
    # "pylsp-memestra",
    "pylsp-mypy",
    "pylsp-rope",
    "pytest",
    "fastapi[standard]>=0.115.12",
]

[tool.ruff]
line-length = 88
indent-width = 4

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "N",
    "B",
    "C",
    # "D", # Documentation
    # "T", # Prints found
    "R",
    "W",
]
